name: Deploy API

on:
  push:
    branches:
      - main
    paths:
      - 'db/exchangeRates.json'

jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-22.04
    if: github.ref_name == 'main' && github.repository_owner == 'kilimanjjjaro'
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Install dependencies
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Deploy API to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish
