name: Scrape and Deploy API

on:
  schedule:
    - cron: '0 19 * * 1-5'

jobs:
  scrape_and_deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: zcong1993/setup-timezone@master
        with:
          timezone: America/Argentina/Buenos_Aires
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run scrape
      - name: Commit and Push Changes
        run: |
          git config --global user.email "hola@kilimanjjjaro.com"
          git config --global user.name "kili-bot"
          git add .
          git commit -m "[kili-bot] update database"
          git push origin main
      - name: Deploy to Cloudflare Workers
        if: github.ref == 'refs/heads/main'
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish
